### ISSUE TITLE
Исправления

### ISSUE THREAD

**Issue by saippuakauppias** [jsmarkus/the-little-mongodb-book#1]
**Формат исправлений**

`````` строка:опечатка```
```исправление или вопрос```

11: The Little MongoDB Book book is licensed under the Attribution-NonCommercial 3.0 Unported license.
The Little MongoDB Book (Маленькая книга о MongoDB) распространяется под лицензией Attribution-NonCommercial 3.0 Unported.

14: отображать
публиковать

20: частично занятый
не звучит, надо как-то по-другому

20: опен-сорсных
не думаю, что это стоит переводить

20: нерегулярный докладчик
нерегулярный докладчик на конференциях

20: туториал
описание, руководство, учебник - так лучше будет

41: сегодня пять
сегодня их пять

41: NoSQL-решений
NoSQL-решения

43: как правило
, как правило, 

54: драйвера (в 2х местах)
правильнее "драйверы"

60: РАспакуйте
Распакуйте

64: ПУТЬ_КУДА_ХОТЕТИ_СОХРАНИТЬ_ФАЙЛЫ_БАЗЫ_ДАННЫХ
ПУТЬ_КУДА_ХОТИТЕ_СОХРАНИТЬ_ФАЙЛЫ_БАЗЫ_ДАННЫХ

81: механихмов
механизмов

81: доля
для

85: контейнеров
контейнером

107: Заметка на полях.
Думаю, стоит оформить как-то в markdown-синтаксисе, чтоб понятнее было

109: прим. перев.
весь блок примечания, пожалуй, стоит обрамить в "*", чтобы он был выделен курсивом

113: коллекцию `unicorns` передавая
коллекцию `unicorns`, передавая

119: позвольить
позволить

152: //or (not quite the same thing, but for demonstration purposes)
думаю, так же стоит перевести

169: командой `remove`? которую
командой `remove`, которую

171: `ObjectId` сгенерированны MongoDB для поля `_id` подставляется в селектор следующим образом:
пожалуй, правильнее так:
`ObjectId`, сгенерированный MongoDB для поля `_id`, подставляется в селектор следующим образом:

175: В этой главеr
В этой главе

Всё, дальше перевод закончился. Извиняюсь, что вчера так и не ответил по поводу генерации pdf - уснул сразу же после работы :)

p.s.:
Как лучше - по каждому разделу новое Issue?
Используется ли какой-нибудь спелл-чекер?
``````

**Comment by jsmarkus** [comment]
Спасибо за вычитку, буду исправлять по мере возможности.

Spell-checker теперь установил)

Не по каждому разделу новое Issue, а просто по мере накопления таковых.

Кстати, есть успехи с генерацией PDF?

**Comment by saippuakauppias** [comment]
Лучше исправлять в следующем после публикации Issue коммите. Мне бы так было удобнее - я иногда буду перечитывать заново, чтоб посмотреть не возникли какие-нибудь противоречия. Проще говоря - чтоб по два раза одно и то же не писал я :)

Пока не пробовал сгенерить PDF. Сейчас на работе ещё, как буду дома - обязательно попробую.

**Comment by jsmarkus** [comment]
Да, так будет лучше.

А PDF ругается на multibyte-последовательности. Вообще там у автора как-то перемудрено, да еще и на LaTeX завязано. Возможно, следует вообще генерировать PDF как-то по-другому.

**Comment by jsmarkus** [comment]
Плюс - автор юзает несвободные шрифты...
